### PR TITLE
Add debug overlay

### PR DESCRIPTION
**Pull request by Hacksore**
Added a feature to enable debug information as an overlay canvas for debugging position of the camera.

It adds a new class `DebugCanvas` which is a proprty of `SkinViewer` and to enable it you call `skinViewer.debugCanvas.setState(true)`.

image

It'd be much nicer to just have this canvas render onto the three.js scene because a big limitation to my approach is it's very depentant on a parent dom element wrapper for the canvas.

In any case, the PR is up for discussion/suggestions.

### CODE REVIEW

**Comment by yushijinhun** [comment]
IMO, the debug overlay should exist only in the demo, not in the source.

**Comment by Hacksore** [comment]
@yushijinhun Can it be something like a standalone repo similar to how the Three.js stats works?

**Comment by yushijinhun** [comment]
I think this is what we need: https://github.com/georgealways/lil-gui

**Comment by Hacksore** [comment]
@yushijinhun That looks ok, especially if we want some form of interaction with the camera rather than just read-only.

**Comment by Hacksore** [comment]
If someone wants to just add some basic debug to the demo without messing with the viewer source that'd be sufficient. I really don't think we want to add [lil-gui](https://github.com/georgealways/lil-gui) to the demo after more consideration since it's meant to stay basic.

Going to close this PR for now as I haven't had time to revisit it.

**Pull request closed without merging**
