### PR TITLE
Split utils.ts into a separate package

### PR DESCRIPTION
**Pull request by yushijinhun**
I've split [`utils.ts`](https://github.com/bs-community/skinview3d/blob/75f6d7bf659a646c7f105f1bb160c8fe595f40b0/src/utils.ts) into a separate npm package [`@yushijinhun/skinview-utils`](https://github.com/yushijinhun/skinview-utils). This would allow us to use the utilities in other projects.

Currently, this package is scoped because it's just experimental. I will change the package name to `skinview-utils` after it's ready.

TODOs:
- [x] consensus on the plan
- [x] migrate testcases (https://github.com/yushijinhun/skinview-utils/commit/70be788490b53b948fe1f8fe7d27947bd55b1dcd, https://github.com/bs-community/skinview3d/pull/45/commits/f4565bc99be3b6828f40b992ad3d844a0134406c)
- [x] transfer `skinview-utils` to bs-community
- [x] move `skinview-utils` out of my username scope (https://github.com/bs-community/skinview-utils/commit/ee844685b5934a45e6c02d3a6a0d717da6efa88a)

Related: #44 

/cc @Hacksore @g-plane

### CODE REVIEW

**Comment by yushijinhun** [comment]
A question: should `skinview-utils` be in `dependencies` or `devDependencies`?

I prefer to keep skinview3d in one js file, so I'm going to bundle it in skinview3d.

**Comment by Hacksore** [comment]
@yushijinhun I think you want to setup a CI build agent for `skinview-utils` as well so the test can run.

**Comment by yushijinhun** [comment]
Some plans about this after discussion with @g-plane:
 * skinview-utils will be a dependency of skinview3d (not dev dependency).
 * skinview-utils will be bundled in skinview3d, and `skinview3d.(min.)js` will continue to be a single file.
    * But skinview3d no longer exports what was originally in `utils.ts`, such as `isSlimSkin()`.
 * `skinview3d.module.js` will be replaced by multiple ES modules, which allows tree-shaking.
    * And the package structure will be like:
        ```
         - dist/ (UMD modules)
            * skinview3d.js
            * skinview3d.min.js (the 'main' entrypoint)
         - jsm/ (ES6 modules)
            * skinview3d.js (the 'module' entrypoint)
            * skinview3d.d.ts
            * viewer.js
            * viewer.d.ts
            ...
        ```

@Hacksore How do you like it?

**Comment by g-plane** [comment]
I advise to rename `jsm` to `esm` since it means "ES Module".

**Comment by yushijinhun** [comment]
> I advise to rename `jsm` to `esm` since it means "ES Module".

But [three.js](https://github.com/mrdoob/three.js/tree/dev/examples/jsm) uses `jsm`. Is there any convention on this? If not, I think it's better to follow three.js.

**Comment by g-plane** [comment]
> Is there any convention on this?

No.

**Pull request merged**
