### PR TITLE
Added animated capes and ears

### PR DESCRIPTION
**Pull request by james090500**
This PR adds animated capes and ears. It makes signifant changes to both SkinView3D and SkinView-Utils. There may be better ways of doing what I'm doing but unsure at the moment, feedback is appreciated. 

The Package.json still contains a reference to the local dev build of skinviewutils but I am unsure how to counter this for testing as in its native state building will fail.

However, this does fully work currently. 

https://streamable.com/0o3968

### CODE REVIEW

**Comment by withdrew** [comment]
This would be cool

**Comment by Hibiii** [comment]
There are no official animated capes, I don't see why that's a needed feature.

**Comment by yushijinhun** [comment]
I've just implemented ears.

**Comment by TheKodeToad** [comment]
> There are no official animated capes, I don't see why that's a needed feature.

There are no official wings either and the corresponding issue hasn't been closed yet, so I personally think this is a good suggestion.

**Comment by james090500** [comment]
This looks to be fully implemented.

**Pull request closed without merging**
