### PR TITLE
Refactor animations & controls

### PR DESCRIPTION
**Pull request by yushijinhun**
Motivations:
- In most cases, we want to use `OrbitControls` to enable mouse control function. It's better to integrate it into `SkinViewer`.
- The current animation system which allows multiple animations to co-exist is over-designed. It's obvious that animations can't co-exist in most cases. Therefore, I want to refactor the animation system to make it simpler.

Changes:
- `OrbitControls` is integrated into `SkinViewer` (`SkinViewer.controls` property).
- Only one animation is allowed at a time (`SkinViewer.animation` property).
- `RotatingAnimation` is removed.
  - Instead, you can use `SkinViewer.controls.autoRotate` to rotate the camera.
  - However, if the scene background is a panoramic image, rotating the camera will also change the background, while rotating the player will not. I don't know if it's a problem.

I'm uncertain whether these changes are appropriate, so please give me your opinions on this.

Since all these changes are breaking changes, if this PR got merged, the next version would be `v3.0`.

/cc @Hacksore @g-plane

### CODE REVIEW

**Comment by Hacksore** [comment]
@yushijinhun Could you publish this to npm as @next so I can play around with it and add my feedback?

**Comment by g-plane** [comment]
You can switch to the `refactor-animations` branch then link this repository to another project by using `npm link` or Yarn or pnpm.

**Comment by Hacksore** [comment]
@g-plane I was hoping to setup a demo on codesandbox.io or stackblitz.com then share it here but it's very finicky when trying to import from the source 😞.

**Comment by yushijinhun** [comment]
@bribes Thanks for your suggestions. I've added the `SkinViewer.autoRotate` and the `SkinViewer.autoRotateSpeed` property, which control the rotation of the player.

**Comment by yushijinhun** [comment]
@Hacksore You can upload the `.tgz` tarball to CodeSandbox. Here's the example: https://codesandbox.io/s/crazy-dawn-kev5co?file=/src/index.js

**Pull request merged**
