### PR TITLE
Include separate modules in build output

### PR DESCRIPTION
**Pull request by yushijinhun**
Origin: https://github.com/bs-community/skinview3d/pull/45#issuecomment-575554703

* Removed `dist/skinview3d.js`, `dist/skinview3d.module.js`, `dist/*.d.ts`.
    * Sourcemap is added, so we no longer need non-minified version.
* Added directory `jsm`.
* Target is changed to ES2015.
* The package structure will be like:
    ```
     - dist/ (UMD modules)
        * skinview3d.min.js
        * skinview3d.min.js.map
     - jsm/ (ES6 modules)
        * skinview3d.js (the 'main' entrypoint)
        * skinview3d.js.map
        * skinview3d.d.ts
        * viewer.js
        * viewer.js.map
        * viewer.d.ts
        ...
    ```
* For UMD modules:
    * skinview-utils is bundled but not exported, since we are using it internally.
    * three.js is not bundled.
* UMD vs ES6 modules:
    * **UMD**: Use it if you don't want to waste time on configuring bundlers (rollup, webpack, etc).
    * **ES6**: For those who want to use tree-shaking or other features.

### CODE REVIEW

**Comment by g-plane** [comment]
Have you tested manually?

**Comment by yushijinhun** [comment]
> Have you tested manually?

Yes.

**Comment by g-plane** [comment]
图片

图片

**Comment by yushijinhun** [comment]
I suggest we take this approach: [Approach #2: Isolate State](https://nodejs.org/api/esm.html#esm_approach_2_isolate_state)

**Comment by yushijinhun** [comment]
After discussion with @g-plane, I'm going to use ES6 modules only and remove UMD modules, since ES6 modules & HTTP/2 have been widely supported.

This is not a final decision and may be changed in the future. If pure ES6 modules work fine, it will be in v2.0. If not, we will seek alternative approaches.

**Comment by yushijinhun** [comment]
image

It works fine now in vscode.

**Comment by yushijinhun** [comment]
> This does not seem right?

It seems that omitting `.js` extension is not recommended. Meanwhile, typescript understands that `xxx.js` actually refers to `xxx.ts`.

- https://github.com/microsoft/TypeScript/issues/16577
- https://nodejs.org/api/esm.html#esm_resolution_algorithm

**Comment by yushijinhun** [comment]
@Hacksore Omitting the `.js` extension is not supported by NodeJS and browsers. If we are going to support importing skinview3d as an ES module (in browsers), we have to append `.js` extension to module specifiers.

**Pull request merged**
